apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      # redinessProbe:
      #   initialDelaySeconds: 10
        # httpGet:
        #    path: /
        #    port: 8080   
      # livenessProbe:
      #   initialDelaySeconds: 15
      #    httpGet: 
      #       path: /
      #       port: 8080
      containers:
      - name: spring-petclinic-ecr
        image: nginx:latest
        ports:
        - containerPort: 80
